language: php

php:
   - "7.0"
   - "7.1"
   - hhvm
   - nightly



matrix:
    allow_failures:
        - php: nightly
        - php: hhvm



sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    # Prepare for automated tests
    - make install
    - make check



script:
    # Run tests
    - make test
